### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'no_args_is_help'

### ISSUE THREAD

**Issue by emonhossainraihan** [AntonBallmaier/manim#9]
## Description of bug / unexpected behavior

Once I know that pull request [1347](https://www.reddit.com/r/manim/comments/mwfvq9/manim_is_not_behaving_properly/) has some extra feature like `start_animation` method on `StreamLines` class, I was curious enough to try your version. After check out 
vector-field-docs branch I try to experiment `start_animation` method but got an error:

```
TypeError: __init__() got an unexpected keyword argument 'no_args_is_help'
```

## Expected behavior

I was expecting what showed [here](https://manimce--1347.org.readthedocs.build/en/1347/reference/manim.mobject.vector_field.StreamLines.html#continuousmotion)

https://user-images.githubusercontent.com/34622219/115864936-6f394180-a459-11eb-8e60-0b1c59001541.mp4

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
class ContinuousMotion(Scene):
    def construct(self):
        func = lambda pos: np.sin(pos[0]/2)*UR+np.cos(pos[1]/2)*LEFT
        stream_lines = StreamLines(
            func, stroke_width=3,
            max_anchors_per_line=30
        )
        self.add(stream_lines)
        stream_lines.start_animation(warm_up=False, flow_speed=1.5)
        self.wait(stream_lines.virtual_time / stream_lines.flow_speed)
```

</details>

## Logs
<details><summary>Terminal output</summary>

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/emonhossain/Desktop/1347/manim/manim/__init__.py", line 92, in <module>
    from .utils.ipython_magic import ManimMagic
  File "/home/emonhossain/Desktop/1347/manim/manim/utils/ipython_magic.py", line 10, in <module>
    from manim.__main__ import main
  File "/home/emonhossain/Desktop/1347/manim/manim/__main__.py", line 7, in <module>
    from .cli.cfg.commands import cfg
  File "/home/emonhossain/Desktop/1347/manim/manim/cli/cfg/commands.py", line 138, in <module>
    def write(level: str = None, openfile: bool = False) -> None:
  File "/usr/lib/python3/dist-packages/click/core.py", line 1234, in decorator
    cmd = command(*args, **kwargs)(f)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 115, in decorator
    cmd = _make_command(f, name, attrs, cls)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 88, in _make_command
    return cls(name=name or f.__name__.lower().replace('_', '-'),
TypeError: __init__() got an unexpected keyword argument 'no_args_is_help'
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)): Ubuntu 20.04
- RAM: 8 GB
- Python version (`python/py/python3 --version`): 3.8.5
- Installed modules (provide output from `pip list`):
```
Package                Version
---------------------- --------------------
appdirs                1.4.3
apturl                 0.5.2
argon2-cffi            20.1.0
async-generator        1.10
attrs                  20.3.0
backcall               0.2.0
bcrypt                 3.1.7
beautifulsoup4         4.8.2
bleach                 3.3.0
blessings              1.7
blinker                1.4
bpython                0.21
Brlapi                 0.7.0
certifi                2019.11.28
cffi                   1.14.5
chardet                3.0.4
chrome-gnome-shell     0.0.0
Click                  7.0
click-default-group    1.2.2
cloudpickle            1.6.0
colorama               0.4.3
colour                 0.1.5
command-not-found      0.3
commonmark             0.9.1
cryptography           2.8
cupshelpers            1.0
curtsies               0.3.5
cwcwidth               0.1.4
cycler                 0.10.0
dbus-python            1.2.16
decorator              4.4.2
defer                  1.0.6
defusedxml             0.7.1
distlib                0.3.0
distro                 1.4.0
distro-info            0.23ubuntu1
duplicity              0.8.12.0
entrypoints            0.3
fasteners              0.14.1
filelock               3.0.12
future                 0.18.2
glcontext              2.3.2
gpg                    1.13.1-unknown
greenlet               1.0.0
html5lib               1.0.1
httplib2               0.14.0
idna                   2.8
imageio                2.9.0
importlib-metadata     1.5.0
ipykernel              5.5.3
ipython                7.20.0
ipython-genutils       0.2.0
ipywidgets             7.6.3
jedi                   0.18.0
Jinja2                 2.11.3
jsonschema             3.2.0
jupyter                1.0.0
jupyter-client         6.1.12
jupyter-console        6.4.0
jupyter-core           4.7.1
jupyterlab-pygments    0.1.2
jupyterlab-widgets     1.0.0
keyring                18.0.1
kiwisolver             1.3.1
language-selector      0.1
launchpadlib           1.10.13
lazr.restfulclient     0.14.2
lazr.uri               1.0.3
linecache2             1.0.0
lockfile               0.12.2
louis                  3.12.0
lxml                   4.5.0
macaroonbakery         1.3.1
Mako                   1.1.0
manim                  0.5.0
manim-fonts            0.1.0.post4
manim-rubikscube       0.0.8
ManimPango             0.2.4
mapbox-earcut          0.12.10
MarkupSafe             1.1.0
mathinspector          0.9.3.post0
matplotlib             3.3.4
mistune                0.8.4
moderngl               5.6.4
moderngl-window        2.3.0
monotonic              1.5
more-itertools         4.2.0
mpmath                 1.2.1
multipledispatch       0.6.0
nbclient               0.5.3
nbconvert              6.0.7
nbformat               5.1.3
nest-asyncio           1.5.1
netifaces              0.10.4
networkx               2.5
notebook               6.3.0
numpy                  1.20.1
oauthlib               3.1.0
olefile                0.46
opencv-python          4.5.1.48
packaging              20.9
pandocfilters          1.4.3
paramiko               2.6.0
parso                  0.8.1
pbr                    5.4.5
pexpect                4.6.0
pickleshare            0.7.5
Pillow                 7.0.0
pip                    21.0.1
progressbar            2.5
prometheus-client      0.10.1
prompt-toolkit         3.0.16
protobuf               3.6.1
ptyprocess             0.7.0
pycairo                1.20.0
pycparser              2.20
pycups                 1.9.73
pydub                  0.24.1
pygame                 2.0.1
pyglet                 1.5.15
PyGLM                  1.99.3
Pygments               2.8.0
PyGObject              3.36.0
PyJWT                  1.7.1
pymacaroons            0.13.0
PyNaCl                 1.3.0
PyOpenGL               3.1.5
PyOpenGL-accelerate    3.1.5
pyparsing              2.4.7
PyQt5                  5.14.1
pyRFC3339              1.1
pyrr                   0.10.3
pyrsistent             0.17.3
PySocks                1.6.8
python-apt             2.0.0+ubuntu0.20.4.4
python-dateutil        2.7.3
python-debian          0.1.36ubuntu1
pytz                   2019.3
PyWavelets             1.1.1
pyxdg                  0.26
PyYAML                 5.3.1
pyzmq                  22.0.3
qtconsole              5.0.3
QtPy                   1.9.0
reportlab              3.5.34
requests               2.22.0
requests-unixsocket    0.2.0
rich                   6.2.0
scikit-image           0.18.1
scipy                  1.6.1
scour                  0.37
screeninfo             0.6.7
SecretStorage          2.3.1
Send2Trash             1.5.0
setuptools             53.0.0
simplejson             3.16.0
sip                    4.19.21
six                    1.14.0
soupsieve              1.9.5
sympy                  1.7.1
systemd-python         234
terminado              0.9.4
testpath               0.4.4
testresources          2.0.0
tifffile               2021.3.17
torbrowser-launcher    0.3.2
tornado                6.1
tqdm                   4.57.0
traceback2             1.4.0
traitlets              5.0.5
ttkthemes              2.0.6
typing-extensions      3.7.4.3
ubuntu-advantage-tools 20.3
ubuntu-cleaner         1.1.3
ubuntu-drivers-common  0.0.0
ufw                    0.36
unattended-upgrades    0.1
unittest2              1.1.0
urllib3                1.25.8
usb-creator            0.3.7
validators             0.18.2
virtualenv             20.0.17
wadllib                1.3.3
watchdog               2.0.2
wcwidth                0.2.5
webencodings           0.5.1
wheel                  0.36.2
widgetsnbextension     3.5.1
xkit                   0.0.0
zipp                   1.0.0

```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100

```
</details>

**Comment by AntonBallmaier** [comment]
Judging from your output log this doesn't seem to be based on the vectorfield module, since it isn't even in the stack trace. Please Try to narrow down the problem and report the bug in the manimCE repo.
